// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleManager.Data;

#nullable disable

namespace ScheduleManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405182959_AddCRUDapis")]
    partial class AddCRUDapis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScheduleManager.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 10,
                            Name = "10A1",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Grade = 11,
                            Name = "11B2",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            Grade = 12,
                            Name = "12C3",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("ScheduleManager.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tổ Toán - Lý - Tin",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tổ Văn - Sử - Địa",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("ScheduleManager.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            DayOfWeek = 1,
                            Period = 1,
                            SchoolId = 1,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            DayOfWeek = 1,
                            Period = 2,
                            SchoolId = 1,
                            SubjectId = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 2,
                            DayOfWeek = 2,
                            Period = 1,
                            SchoolId = 1,
                            SubjectId = 3,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            DayOfWeek = 2,
                            Period = 2,
                            SchoolId = 1,
                            SubjectId = 4,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 3,
                            DayOfWeek = 3,
                            Period = 1,
                            SchoolId = 1,
                            SubjectId = 5,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 1,
                            DayOfWeek = 3,
                            Period = 2,
                            SchoolId = 1,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 2,
                            DayOfWeek = 4,
                            Period = 1,
                            SchoolId = 1,
                            SubjectId = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 3,
                            DayOfWeek = 4,
                            Period = 2,
                            SchoolId = 1,
                            SubjectId = 3,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 1,
                            DayOfWeek = 5,
                            Period = 1,
                            SchoolId = 1,
                            SubjectId = 4,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 2,
                            DayOfWeek = 5,
                            Period = 2,
                            SchoolId = 1,
                            SubjectId = 6,
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("ScheduleManager.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trường THPT Nguyễn Du"
                        });
                });

            modelBuilder.Entity("ScheduleManager.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Toán",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Vật Lý",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Tin Học",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Ngữ Văn",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Lịch Sử",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Name = "Địa Lý",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("ScheduleManager.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Nguyễn Văn An",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Trần Thị Bình",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Lê Văn Cường",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Phạm Thị Dung",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Hoàng Văn Ê",
                            SchoolId = 1
                        });
                });

            modelBuilder.Entity("ScheduleManager.Models.Class", b =>
                {
                    b.HasOne("ScheduleManager.Models.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ScheduleManager.Models.Department", b =>
                {
                    b.HasOne("ScheduleManager.Models.School", "School")
                        .WithMany("Departments")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ScheduleManager.Models.Schedule", b =>
                {
                    b.HasOne("ScheduleManager.Models.Class", "Class")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleManager.Models.School", "School")
                        .WithMany("Schedules")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleManager.Models.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleManager.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ScheduleManager.Models.Subject", b =>
                {
                    b.HasOne("ScheduleManager.Models.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleManager.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ScheduleManager.Models.Teacher", b =>
                {
                    b.HasOne("ScheduleManager.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScheduleManager.Models.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ScheduleManager.Models.Class", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ScheduleManager.Models.Department", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("ScheduleManager.Models.School", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Departments");

                    b.Navigation("Schedules");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("ScheduleManager.Models.Subject", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ScheduleManager.Models.Teacher", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
